- hosts: all

  tasks:
    - name: "Instala unzip"
      shell: "sudo apt install unzip -y"
      
    - name: "Instala mvn"
      shell: "sudo apt install maven -y"

    - name: 'add open jdk repository'
      apt_repository:
        repo: 'ppa:openjdk-r/ppa'
        state: present
        update_cache: yes
      become: yes

    - name: 'Install open jdk and git'
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - openjdk-8-jdk
        - git        

    - name: 'set java version 8 as main'
      alternatives:
        name: java
        path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java 


    - name: update certificate java
      shell: update-ca-certificates -f
      become: yes

  
    - name: "Roda: sudo apt-get update"
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #Um dia