- hosts: all

  tasks:
    - name: install update and packages required by docker
      become: true
      apt:
        update_cache: yes
        state: stable # latest
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          # - apt-transport-https
          # - ca-certificates
          # - curl
          # - gpg-agent
          # - software-properties-common

    - name: add docker GPG key
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker apt repo
      become: true
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
        # echo \
        # "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
        # $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: install docker engine
      become: true
      apt:
        update_cache: yes
        state: latest
        name:
        - docker-ce
        - docker-ce-cli
        - containerd.io

          ### To install a specific version of Docker Engine
          ## List the versions available in your repo:
          #  apt-cache madison docker-ce

          ## Install a specific version using the version string from the second column, for example, 5:18.09.1~3-0~ubuntu-xenial.
          #  sudo apt-get install docker-ce=<VERSION_STRING> docker-ce-cli=<VERSION_STRING> containerd.io

          ### If you cannot use Docker’s repository to install Docker Engine, you can download the .deb file for your release and install it manually. You need to download a new file each time you want to upgrade Docker.
          ## Install Docker Engine, changing the path below to the path where you downloaded the Docker package.
          #  sudo dpkg -i /path/to/package.deb

    - name: "Restart docker"
      shell: sudo systemctl restart docker
      become: yes

    - name: "Fazer pull do docker"
      shell: "docker pull ernanecl/app-java-validacao-cnpj"
      become: yes

    - name: "Executar o container"
      shell: "docker run -d -p 3000:3000 --name app-java-validacao-cnpj ernanecl/app-java-validacao-cnpj"
      become: yes

## Links para + conteúdos
# https://docs.docker.com/engine/install/ubuntu/