- hosts: all

  tasks:
    # update do sistema
    - name: "Roda: sudo apt update"
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
        
    # intalando app de descompactação de zip
    - name: "Instalar unzip"
      shell: "sudo apt install unzip -y"
      
    # instalando mvn, uma ferramenta de automação de compilação utilizada primariamente em projetos Java
    - name: "Instalar mvn"
      shell: "sudo apt install maven -y"

    # adicionando repositório jdk (Java Devlopment Kit)
    # um conjunto de utilitários que permitem criar sistemas de software para a plataforma Java. É composto por compilador e bibliotecas.
    - name: 'add open jdk repository'
      apt_repository:
        repo: 'ppa:openjdk-r/ppa'
        state: present
        update_cache: yes
      become: yes

    # instalando jdk e git
    - name: 'Install open jdk and git'
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - openjdk-8-jdk
        - git        

    # definindo java 8 como principal
    - name: 'set java version 8 as main'
      alternatives:
        name: java
        path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

    # atualizando certificado Java
    - name: update certificate java
      shell: update-ca-certificates -f
      become: yes

    # executando atualização do sistema
    - name: "Running: sudo apt-get update"
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #Um dia